controller_manager:
  ros__parameters:
    update_rate: 125

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      joints:
        - j1
        - j2
        - j3
        - j4
        - j5
        - j6

    fairino5_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - j1
        - j2
        - j3
        - j4
        - j5
        - j6
      command_interfaces:
        - position
      state_interfaces:
        - position

joint_state_broadcaster:
  ros__parameters:
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6

fairino5_controller:
  ros__parameters:
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6

    command_interfaces:
      - position

    state_interfaces:
      - position
